#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the factorial function below.
import sys

def factorial(n):
    return 1 if n == 1 else (n * factorial(n - 1))

if __name__ == "__main__":
    n = int(input().strip())
    result = factorial(n)
    print(result)
